title: Your awesome title
email: hello@petragulicher.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

github_url: https://github.com/petronbot
instagram_url: https://www.instagram.com/petronbot/
twitter_url: http://twitter.com/petronbot
linkedin_url: https://www.linkedin.com/in/petragulicher

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - node_modules

collections:
  case-studies:
    title: Case studies
    output: true

defaults:
  -
    scope:
      path: ""
      type: case-studies
    values:
      layout: case-study

safe: FALSE

sass:
  load_paths:
    - _sass
    - node_modules
